### PR TITLE
Change to package.json

### PR DESCRIPTION
**Pull request by 2hands10fingers**
Added and removed special start and build commands

### CODE REVIEW

**Comment by newswim** [comment]
I think you may need to also add `npm-run-all` as a dev dependency:
```
yarn add npm-run-all --dev
```

**Comment by 2hands10fingers** [comment]
@newswim Interesting. Okay, I'll take a stab at it and let me know if this is what you're looking for.

**Comment by newswim** [comment]
Close! The package.json should have a `devDependencies` key with the library and version number. The key doesn't exist currently because there aren't any other dev dependencies. What you'll end up with should look something like this (with whatever the current version is):

```json
  "devDependencies": {
    "npm-run-all": "^1.0"
  }
```

You can just remove the line from that last commit and run `yarn add npm-run-all --dev` and that line will be created for you.

**Comment by newswim** [comment]
I'll go ahead and merge this and then make the changes in a new PR

**Pull request merged**
